export const apiKey = '9a2054ac465c496bb8e181843241503';

export const weatherImageDay = {
//     'Parcialmente nublado': require('../assets/images/partlycloudy.png'),
//     'Moderate rain': require('../assets/images/moderaterain.png'),
//     'Patchy rain possible': require('../assets/images/moderaterain.png'),
//     'Sunny': require('../assets/images/sun.png'),
//     'Clear': require('../assets/images/sun.png'),
//     'Overcast': require('../assets/images/cloud.png'),
//     'Cloudy': require('../assets/images/cloud.png'),
//     'Light rain': require('../assets/images/moderaterain.png'),
//     'Moderate rain at time': require('../assets/images/moderaterain.png'),
//     'Heavy rain': require('../assets/images/heavyrain.png'),
//     'Heavy rain at times': require('../assets/images/heavyrain.png'),
//     'Moderate or heavy freezing rain': require('../assets/images/heavyrain.png'),
//     'Moderate or heavy rain shower': require('../assets/images/heavyrain.png'),
//     'Moderate or heavy rain with thunder': require('../assets/images/heavyrain.png'),
//     'other': require('../assets/images/moderaterain.png'),
//

    '1000': require('../assets/images/sun.png'),
    '1003': require('../assets/images/partlycloudy.png'),
    '1006': require('../assets/images/cloud.png'),
    '1009': require('../assets/images/cloud.png'),
    '1030': require('../assets/images/cloudy.png'),
    '1063': require('../assets/images/rainy.png'),  
    '1066': require('../assets/images/snowing.png'),
    '1069': require('../assets/images/snowing.png'),
    '1072': require('../assets/images/moderaterain.png'),
    '1087': require('../assets/images/heavyrain.png'),
    '1114': require('../assets/images/snow-storm.png'),
    '1117': require('../assets/images/snow-storm.png'),
    '1135': require('../assets/images/cloudy.png'),
    '1147': require('../assets/images/cloudy.png'),
    '1150': require('../assets/images/moderaterain.png'),
    '1153': require('../assets/images/moderaterain.png'),
    '1168': require('../assets/images/moderaterain.png'),
    '1171': require('../assets/images/moderaterain.png'),
    '1180': require('../assets/images/moderaterain.png'),
    '1183': require('../assets/images/moderaterain.png'),
    '1186': require('../assets/images/moderaterain.png'),
    '1189': require('../assets/images/moderaterain.png'),
    '1192': require('../assets/images/moderaterain.png'),
    '1195': require('../assets/images/moderaterain.png'),
    '1198': require('../assets/images/moderaterain.png'),
    '1201': require('../assets/images/moderaterain.png'),
    '1204': require('../assets/images/snowing.png'),
    '1207': require('../assets/images/snowing.png'),
    '1210': require('../assets/images/snowing.png'),
    '1213': require('../assets/images/snowing.png'),
    '1216': require('../assets/images/snowing.png'),
    '1219': require('../assets/images/snowing.png'),
    '1222': require('../assets/images/snowing.png'),
    '1225': require('../assets/images/snowing.png'),
    '1237': require('../assets/images/snowing.png'),
    '1240': require('../assets/images/moderaterain.png'),
    '1243': require('../assets/images/moderaterain.png'),
    '1246': require('../assets/images/heavyrain.png'),
    '1249': require('../assets/images/snowing.png'),
    '1252': require('../assets/images/snowing.png'),
    '1255': require('../assets/images/snowing.png'),
    '1258': require('../assets/images/snowing.png'),
    '1261': require('../assets/images/freezing-rain.png'),
    '1264': require('../assets/images/freezing-rain.png'),
    '1273': require('../assets/images/heavyrain.png'),
    '1276': require('../assets/images/heavyrain.png'),
    '1279': require('../assets/images/heavyrain.png'),
    '1282': require('../assets/images/heavyrain.png'),
}

export const weatherImageNight = {
    '1000': require('../assets/images/night-mode.png'),
    '1003': require('../assets/images/half-moon.png'),
    '1006': require('../assets/images/cloud.png'),
    '1009': require('../assets/images/cloud.png'),
    '1030': require('../assets/images/cloudy.png'),
    '1063': require('../assets/images/moderaterain.png'),
    '1066': require('../assets/images/snowing.png'),
    '1069': require('../assets/images/snowing.png'),
    '1072': require('../assets/images/moderaterain.png'),
    '1087': require('../assets/images/heavyrain.png'),
    '1114': require('../assets/images/snowing.png'),
    '1135': require('../assets/images/snowing.png'),
    '1147': require('../assets/images/cloudy.png'),
    '1150': require('../assets/images/cloudy.png'),
    '1153': require('../assets/images/moderaterain.png'),
    '1168': require('../assets/images/moderaterain.png'),
    '1171': require('../assets/images/moderaterain.png'),
    '1180': require('../assets/images/moderaterain.png'),
    '1183': require('../assets/images/moderaterain.png'),
    '1186': require('../assets/images/moderaterain.png'),
    '1189': require('../assets/images/moderaterain.png'),
    '1192': require('../assets/images/moderaterain.png'),
    '1195': require('../assets/images/moderaterain.png'),
    '1198': require('../assets/images/moderaterain.png'),
    '1201': require('../assets/images/moderaterain.png'),
    '1204': require('../assets/images/snowing.png'),
    '1207': require('../assets/images/snowing.png'),
    '1210': require('../assets/images/snowing.png'),
    '1213': require('../assets/images/snowing.png'),
    '1216': require('../assets/images/snowing.png'),
    '1219': require('../assets/images/snowing.png'),
    '1222': require('../assets/images/snowing.png'),
    '1225': require('../assets/images/snowing.png'),
    '1237': require('../assets/images/freezing-rain.png'),
    '1240': require('../assets/images/moderaterain.png'),
    '1243': require('../assets/images/moderaterain.png'),
    '1246': require('../assets/images/moderaterain.png'),
    '1249': require('../assets/images/snowing.png'),
    '1252': require('../assets/images/snowing.png'),
    '1255': require('../assets/images/snowing.png'),
    '1258': require('../assets/images/snowing.png'),
    '1261': require('../assets/images/freezing-rain.png'),
    '1264': require('../assets/images/freezing-rain.png'),
    '1273': require('../assets/images/heavyrain.png'),
    '1276': require('../assets/images/heavyrain.png'),
    '1279': require('../assets/images/heavyrain.png'),
    '1282': require('../assets/images/heavyrain.png'),
}